# Generated by Django 3.1.7 on 2021-02-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210225_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(default='null', max_length=128, verbose_name='型号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(default='null', max_length=128, verbose_name='平台(netmiko)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='series',
            field=models.CharField(default='null', max_length=128, verbose_name='系列'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='ip',
            field=models.CharField(max_length=128, verbose_name='IP地址（fqdn）'),
        ),
    ]
