# Generated by Django 3.1.7 on 2021-02-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210225_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=22, verbose_name='ssh端口'),
        ),
    ]
