# Generated by Django 3.1.7 on 2021-02-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_device_port'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='creted_time',
            new_name='created_time',
        ),
    ]
