# Generated by Django 2.2.10 on 2020-02-22 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('name', models.CharField(max_length=128, verbose_name='设备名')),
                ('vendor', models.CharField(max_length=128, verbose_name='厂商')),
                ('start_u', models.IntegerField(verbose_name='开始U位')),
                ('end_u', models.IntegerField(verbose_name='结束U位')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.AddField(
            model_name='arp',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Device', verbose_name='设备'),
        ),
    ]
