---
- name: 执行思科nxos show命令 # play的名称 选填，建议使用
  hosts: cisco_nxos  # filter网络设备
  gather_facts: no # 收集设备的一些基础信息。比如端口、版本、平台等等，耗费时间，大家都选择不调用
  tasks:
    - name: 执行show命令
      nxos_command: 
        commands: 
          - terminal length 0 # 去掉分页，这个非常关键
          - show version # 执行show 配置的命令，保证所有配置可以一次回显到stdout中
      register: show_text # 将结果注册到变量show_text中，你也可以起其他的名字
    
    - name: Dispaly show text in msg 
      debug: msg="this is a debug message：{{ show_text }}"

    # msg隐藏模式，可以用列表操作
    - name: Dispaly show text in msg with loop
      debug: 
        msg: "this is one command show {{ item }}"
      loop: "{{ show_text.stdout_lines[1] }}" # 注意下标

    - name: Dispaly show text in msg with loop
      debug: msg="this is a debug message： {% for lines in  show_text.stdout_lines %} {% for line in  lines %} {{ line }} \n {%endfor%} {%endfor%}"

    - name: Dispaly show text in var
      debug: var=show_text

    - name: Dispaly show text in var with python style
      debug: var=show_text['stdout_lines']

    - name: Dispaly show text in var with jinja2 style
      debug: var=show_text.stdout_lines


    - name: copy file in method 1
      copy: 
        content: "{% for lines in  show_text.stdout_lines %} {% for line in  lines %} {{ line }} \n {%endfor%} {%endfor%}"
        dest: "/tmp/{{ansible_host}}_{{lookup('pipe','date +%Y%m%d')}}_show_run_1.log"


    - name: copy file in method 2
      copy: 
        content: "{{ show_text.stdout[1] }}"
        dest: "/tmp/{{ansible_host}}_{{lookup('pipe','date +%Y%m%d')}}_show_run_2.log"

    - name: Create a directory if it does not exist
      file:
        path: "/tmp/{{ansible_host}}/{{lookup('pipe','date +%Y%m%d')}}"
        state: directory
        mode: '0755' # 文件夹设置权限
    
    - name: copy file with dir
      copy: 
        content: "{{ show_text.stdout[1] }}"
        dest: "/tmp/{{ansible_host}}/{{lookup('pipe','date +%Y%m%d')}}/show_run_2.log" # 文件夹必须存在，不存在报错