---
- name: 根据模板和变量生成配置文件01-变量内置到playbook
  hosts: all  # filter网络设备
  gather_facts: no # 收集设备的一些基础信息。比如端口、版本、平台等等，耗费时间，大家都选择不调用
  vars:
    interfaces:
      - ['Ethr1/50','configed by ansible templates'] 
      - ['Ethr1/51','configed by ansible templates'] 
      - ['Ethr1/52','configed by ansible templates'] 


  tasks:
    - name: 执行show命令
      template: src=interfaces.j2 dest=/tmp/my{{ansible_host}}.config
