---
netdevops:
  data:
    cmds:
      - display version
      - display interface
ce:
  data:
    cmds_in_group:
      - display version
      - display interface

nxos:
  data:
    cmds_in_group:
      - show version
      - show interface

demo_for_tree:
  hostname: 192.168.56.202
  username: netdevops
  password: Admin123!
  port: 22
  platform: huawei
  data:
    cmds:
      - 1
      - 2
      - 3
  groups:
    - ce
    - nxos

test_group:
    hostname: 192.168.56.202
    username: netdevops
    password: Admin123!
    port: 22
    platform: huawei

leaf:
  data:
    role: leaf
    chongtu_k: 1

bj:
  data:
    city: beijing
    chongtu_k: 2

bj_leaf:
  groups:
    - leaf
    - bj