---
dev01.leaf:
  hostname: 192.168.56.201
  username: netdevops
  password: Admin123!
  port: 22
  platform: huawei
  groups:
    - bj_leaf
    - netdevops
    - ce
  data:
    role: leaf
    tags:
      - test
      - netdevops
      - ce
    cmds:
      - display version
  connection_options:
      extras:
        conn_timeout: 60

dev02.leaf:
  hostname: 192.168.56.202
  username: netdevops
  password: Admin123!
  port: 22
  platform: huawei
  groups:
    - bj_leaf
  data:
    role: leaf
    tags:
      - test
      - netdevops
      - ce
    cmds:
      - display version
  connection_options:
      extras:
        conn_timeout: 60

dev03.spine:
  hostname: sbx-nxos-mgmt.cisco.com
  username: admin
  password: Admin_1234!
  port: 8181
  platform: cisco_nxos
  groups:
    - netdevops
    - nxos
  data:
    role: spine
    info:
      series: nexus 9000
      model: nexus mds 9148
    nonsense_dict:
      a: 1
      b_dict:
        nums:
          - 1
          - 2
          - 3
    tags:
      - nxos
      - core
      - sw
      - production
    cmds:
      - show version
  connection_options:
    netmiko:
      extras:
        conn_timeout: 60